services:
  sakai_mysql:
    image: mysql:5.6.39
    container_name: sakai_mysql
    # Sakai requires the database to use UTF-8.
    command: --character-set-server=utf8
    environment:
      # See https://docs.docker.com/samples/library/mysql/#environment-variables
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: sakaipass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - sakai_mysql:/var/lib/mysql
  sakai:
    build: sakai
    container_name: sakai
    depends_on:
      - sakai_mysql
    environment:
      JAVA_OPTS: -server -Xms512m -Xmx1024m -XX:NewSize=192m -XX:MaxNewSize=384m -Djava.awt.headless=true -Dhttp.agent=Sakai -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false -Dsun.lang.ClassLoader.allowArraySyntax=true -Djava.util.Arrays.useLegacyMergeSort=true # -Dsakai.demo=true
      DATABASE_HOST: sakai_mysql:3306
      DATABASE_NAME: sakai
      DATABASE_USER: sakai
      DATABASE_PASSWORD: sakaipass
      LRS_USERNAME: c278efa00506cb8636ee93d2f9a29085415366ae
      LRS_PASSWORD: cf72e40f90f6d02569a93a44b41f841c32fc41a0
    ports:
      - "8888:8080"
  dummy-xapi:
    build: sakai/dummy-xapi
    container_name: dummy-xapi
    tty: true
    environment:
      TZ: Asia/Tokyo
      STATEMENT_NUM: 300
      TIMESTAMP_MIN: "2021-04-01T00:00:00+00:00"
      TIMESTAMP_MAX: "2021-10-01T00:00:00+00:00"
      LRS_URL: http://learninglocker:8081/data/xAPI/
      LRS_USERNAME: c278efa00506cb8636ee93d2f9a29085415366ae
      LRS_PASSWORD: cf72e40f90f6d02569a93a44b41f841c32fc41a0
  learninglocker:
    image: public.ecr.aws/v8a6v1r8/learninglocker:2.0.0
    container_name: learninglocker
    depends_on:
      - learninglocker_mongo
      - learninglocker_redis
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
    working_dir: /usr/local/src/learninglocker
    command: bash -c "source ~/.bashrc && yarn migrate && pm2 start pm2/all.json && cd ../xapi-service && pm2 start pm2/xapi.json && pm2 logs"
  learninglocker_mongo:
    image: mongo:4.0.8
    container_name: learninglocker_mongo
    volumes:
      - learninglocker_mongo:/data/db
  learninglocker_redis:
    image: redis:5.0.4
    container_name: learninglocker_redis
    volumes:
      - learninglocker_redis:/data
    command: redis-server --appendonly yes
  superset:
    image: public.ecr.aws/v8a6v1r8/superset:2.1.1
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - superset-db
    environment:
      - SECRET_KEY=JmAH_gnn9y5T8Wgjt4IBlzjmYMHEGOQONLuJyfmMMOg
      - ADMIN_USERNAME=admin
      - ADMIN_FIRSTNAME=admin
      - ADMIN_LASTNAME=user
      - ADMIN_EMAIL=admin@fab.org
      - ADMIN_PASSWORD=admin
  superset-db:
    image: public.ecr.aws/v8a6v1r8/superset-db:2.3.1
    container_name: superset-db
    volumes:
      - superset-db:/var/lib/pgsql/9.6/data
    user: postgres
    environment:
      - LRS_HOST=learninglocker_mongo
      - LRS_PORT=27017
      - LRS_DB=learninglocker
      - LRS_DB_USER=
      - LRS_DB_PASSWORD=
      - LRS_COLLECTION=statements
  jupyterhub:
    image: public.ecr.aws/v8a6v1r8/jupyterhub:2.2.0
    container_name: jupyterhub
    ports:
      - "8001:8000"
    volumes:
      - ./notebooks:/home/jupyter
volumes:
  sakai_mysql:
  learninglocker_mongo:
  learninglocker_redis:
  superset-db:
