services:
  log-processor:
    container_name: log-processor
    build: chibichilo/log-processor
  chibichilo-xapi:
    container_name: chibichilo-xapi
    build: chibichilo/xapi
    volumes:
      - ./chibichilo/xapi/log:/app/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
  chibichilo-caliper:
    container_name: chibichilo-caliper
    build: chibichilo/caliper
    env_file:
      - ./chibichilo/caliper/.env
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
