services:
  log_processor:
    container_name: log_processor
    build: chibichilo/log_processor
  xapi_stmt_gen:
    container_name: xapi_video_logs
    build: chibichilo/xapi_stmt_gen
    volumes:
      - ./chibichilo/xapi_stmt_gen/log:/usr/local/src/xapi_stmt_gen/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
  caliper_stmt_gen:
    container_name: caliper_video_logs
    build: chibichilo/caliper_stmt_gen
    env_file:
      - ./chibichilo/caliper_stmt_gen/.env
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
