services:
  log_processor:
    container_name: log_processor
    build: chibichilo/log_processor
  chibichilo-xapi:
    container_name: chibichilo-xapi
    build: chibichilo/xapi
    volumes:
      - ./chibichilo/xapi/log:/app/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
  caliper_stmt_gen:
    container_name: caliper_video_logs
    build: chibichilo/caliper
    env_file:
      - ./chibichilo/caliper/.env
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
