services:
  chibichilo-log-processor:
    build: chibichilo/log-processor
    image: public.ecr.aws/v8a6v1r8/chibichilo-log-processor:1.0.0
    container_name: chibichilo-log-processor
  chibichilo-xapi:
    build: chibichilo/xapi
    image: public.ecr.aws/v8a6v1r8/chibichilo-xapi:1.0.0
    container_name: chibichilo-xapi
    configs:
      - source: xapi-config-app
        target: /app/config/app.js
    volumes:
      - ./chibichilo/xapi/log:/app/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
  chibichilo-caliper:
    build: chibichilo/caliper
    image: public.ecr.aws/v8a6v1r8/chibichilo-caliper:1.0.0
    container_name: chibichilo-caliper
    env_file:
      - ./chibichilo/caliper/.env
    tty: true
    environment:
      - TZ=Asia/Tokyo
    restart: always
configs:
  xapi-config-app:
    file: ./chibichilo/xapi/src/config/app.js
