services:
  moodle:
    image: moodlehq/moodle-php-apache:8.0
    container_name: moodle
    depends_on:
      - moodle-db
    ports:
      - 8080:80
    configs:
      - source: moodle-config
        target: /var/www/html/config.php
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      - MOODLE_DOCKER_DBHOST=moodle-db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=m@0dl3ing
      - MOODLE_DOCKER_MDLURL=http://localhost:8080
      - MOODLE_DOCKER_DATAPATH=/var/www/moodledata
  moodle-db:
    image: postgres:13.8
    container_name: moodle-db
    environment:
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=m@0dl3ing
      - POSTGRES_DB=moodle
    volumes:
      - moodle-db:/var/lib/postgresql/data
configs:
  moodle-config:
    file: ./config.php
volumes:
  moodle-db:
  moodledata:
