services:
  moodle:
    image: moodlehq/moodle-php-apache:8.0
    container_name: moodle
    depends_on:
      - moodle-db
    ports:
      - 8000:80
    configs:
      - source: moodle-config
        target: /var/www/html/config.php
    volumes:
      - ./moodle/moodle:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      - MOODLE_DOCKER_DBHOST=moodle-db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=m@0dl3ing
      - MOODLE_DOCKER_MDLURL=http://localhost:8000
      - MOODLE_DOCKER_DATAPATH=/var/www/moodledata
  moodle-db:
    image: postgres:13.8
    container_name: moodle-db
    environment:
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=m@0dl3ing
      - POSTGRES_DB=moodle
    volumes:
      - moodle-db:/var/lib/postgresql/data
  xapi_stmt_gen:
    build: xapi_stmt_gen
    container_name: xapi_stmt_gen
    volumes:
      - ./moodle/xapi_stmt_gen/log:/usr/local/src/xapi_stmt_gen/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - INTERVAL=-1
  caliper_stmt_gen:
    container_name: caliper_stmt_gen
    build:
      context: caliper
      dockerfile: Dockerfile
    env_file:
      - ./moodle/caliper/.env
    depends_on:
      - caliper_log_db
      - openlrw
      - openlrw_mongo
  learning_analytics_db:
    image: postgres:11
    container_name: learning_analytics_db
    environment:
      - POSTGRES_USER=learning_analytics
      - POSTGRES_PASSWORD=learning_analytics
      - POSTGRES_DB=learning_analytics
    volumes:
      - ./moodle/learning_analytics_db/init:/docker-entrypoint-initdb.d
      - learning_analytics_db:/var/lib/postgresql/data
  caliper_log_db:
    image: postgres:11
    container_name: caliper_log_db
    environment:
      - POSTGRES_USER=caliper_cli
      - POSTGRES_PASSWORD=caliper
      - POSTGRES_DB=caliper_log
    ports:
      - "15432:5432"
    volumes:
      - ./moodle/caliper_log/init:/docker-entrypoint-initdb.d
      - caliper_log_db:/var/lib/postgresql/data
configs:
  moodle-config:
    file: ./moodle/config.php
volumes:
  moodle-db:
  moodledata:
  caliper_log_db:
  learning_analytics_db:
