:encoding: utf-8
:lang: ja
:source-highlighter: rouge
:author: 株式会社Udzuki
:revdate: 2022年2月18日
:revnumber: 1.4.0版
:doctype: book
:version-label:
:chapter-label:
:toc:
:toc-title: 目次
:figure-caption: 図
:table-caption: 表
:example-caption: 例
:appendix-caption: 付録
:toclevels: 2
:pagenums:
:sectnums:
:imagesdir: images
:icons: font

= ラーニングアナリティクス基盤システム: インストール手順
:header-recto-left-content: ラーニングアナリティクス基盤システム  インストール手順
:header-verso-left-content: ラーニングアナリティクス基盤システム  インストール手順


== インストール

----
$ git clone https://github.com/udzuki/Sakai-LMS-LA.git
----

== コンテナイメージのビルド

----
$ cd Sakai-LMS-LA
$ docker-compose build
----

== Learning Locker
Learning Lockerを起動する。

----
$ docker-compose up -d learninglocker
----

https://github.com/RCOSDP/LAaaS-docker/blob/release-v3.0/README.adoc#learning-locker%E3%81%AE%E8%A8%AD%E5%AE%9A[Learning Lockerの設定手順]に従い、xAPIステートメントを保存するLRSを作成する。

[NOTE]
====
Learning Lockerの設定手順 +
https://github.com/RCOSDP/LAaaS-docker/blob/release-v3.0/README.adoc#learning-locker%E3%81%AE%E8%A8%AD%E5%AE%9A
====

== Sakai
`docker-compose.yml` で `sakai` の環境変数 `LRS_USERNAME` および `LRS_PASSWORD` に作成したLRSクライアントの `Key` と `Secret` をそれぞれ設定する。 +
Sakaiが提供するデモデータを起動時に登録する場合には `JAVA_OPTS` で `-Dsakai.demo=true` を指定する。

[[source, diff]]
----
  sakai:
    ...
    environment:
+      JAVA_OPTS: ... -Dsakai.demo=true
       ...
+      LRS_USERNAME: ... # Key
+      LRS_PASSWORD: ... # Secret
----

SakaiのMySQLデータベースを起動する。

----
$ docker-compose up -d sakai_mysql
----

MySQLの起動完了を確認する。

----
$ docker logs -f sakai_mysql

...
MySQL init process done. Ready for start up.

...mysqld: ready for connections.
----

Sakaiコンテナを起動する。

----
$ docker-compose up -d sakai
----

http://localhost:8888/portal からSakaiにアクセスできることを確認する。

== Superset
NOTE: Caliperステートメントの可視化は未対応

Supersetのコンテナを起動する。

----
$ docker-compose up -d superset
----

Sakaiのステートメントを取り扱うため、外部テーブルを変更し、カラムを追加・リネームする。

----
$ docker-compose exec superset-db psql learninglocker -c '
    ALTER FOREIGN TABLE xapi_statements RENAME "statement.object.definition.description.en" TO "statement.object.definition.description.en-US";
    ALTER FOREIGN TABLE xapi_statements RENAME "statement.object.definition.name.en" TO "statement.object.definition.name.en-US";
    ALTER FOREIGN TABLE xapi_statements ADD "statement.result.extensions" VARCHAR;'
----

https://github.com/RCOSDP/LAaaS-docker/blob/release-v3.0/README.adoc#48-superset%E3%81%AE%E8%A8%AD%E5%AE%9A[Supersetの設定手順]に従い、 `xapi_statements` テーブルをSupersetに追加する。

[NOTE]
====
Supersetの設定手順 +
https://github.com/RCOSDP/LAaaS-docker/blob/release-v3.0/README.adoc#48-superset%E3%81%AE%E8%A8%AD%E5%AE%9A
====

== JupyterHub
JupyterHubコンテナを起動する。

----
$ docker-compose up -d jupyterhub
----

[appendix]
== ダミーステートメントの登録

ステートメントの可視化・分析を例示・動作確認する目的において、
Sakaiで実際に操作することなく、 link:../statements/README.adoc[仕様]に則したダミーステートメントを生成するサービス `dummy-xapi` を提供する。

`docker-compose.yml` の `dummy-xapi` で以下に示す環境変数を編集し、ダミーステートメントの生成方法およびステートメントを保存するLRSに関する情報を設定する。

[source, yml]
----
dummy-xapi:
  ...
  environment:
    TZ: Asia/Tokyo
    STATEMENT_NUM: 300 // <1>
    TIMESTAMP_MIN: "2021-04-01T00:00:00+00:00" // <2>
    TIMESTAMP_MAX: "2021-10-01T00:00:00+00:00" // <3>
    LRS_URL: http://learninglocker:8081/data/xAPI/
    LRS_USERNAME: ... // <4>
    LRS_PASSWORD: ... // <4>
----
<1> 登録するダミーステートメントの数
<2> ステートメントに設定するタイムスタンプの最小値
<3> ステートメントに設定するタイムスタンプの最大値
<4> <<Learning Locker>>で作成したLRSクライアントの `Key` と `Secret`

次のコマンドを実行し、LRSにステートメントを登録する。

----
$ docker-compose up -d dummy-xapi
$ docker-compose exec dummy-xapi npm start
----
