name: nii-rcos
channels:
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - intel-openmp=2019.3
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1
  - pandas=0.24.2
  - pymongo=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - six=1.12.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - pip=19.0.3
  - python=3.7.2
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.27.2
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - aniso8601==6.0.0
    - chardet==3.0.4
    - future==0.17.1
    - idna==2.8
    - mccabe==0.6.1
    - pycodestyle==2.5.0
    - pydocstyle==3.0.0
    - pyflakes==2.1.1
    - pylava==0.2.2
    - requests==2.21.0
    - rfc3986==1.1.0
    - snowballstemmer==1.2.1
    - urllib3==1.24.1
