version: '3'
services:
  log_processor:
    container_name: log_processor
    build: log_processor
  xapi_stmt_gen:
    container_name: xapi_video_logs
    build: xapi_stmt_gen
    volumes:
      - ./xapi_stmt_gen/log:/usr/local/src/xapi_stmt_gen/log
    tty: true
    environment:
      - TZ=Asia/Tokyo
  caliper_stmt_gen:
    container_name: caliper_video_logs
    build: caliper_stmt_gen
    env_file:
      - ./caliper_stmt_gen/.env
    tty: true
    environment:
      - TZ=Asia/Tokyo
networks:
  default:
    external:
      name: moodle-docker_default
